# Generated by Django 2.1 on 2018-09-18 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incorporacion', models.DateTimeField(default=datetime.datetime(2018, 9, 18, 15, 39, 16, 367450, tzinfo=utc), verbose_name='fecha de incorporación')),
                ('nombre_y_apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha del turno')),
                ('hora_inicio', models.TimeField(verbose_name='hora inicio')),
                ('duracion', models.IntegerField(verbose_name='duración')),
                ('hora_fin', models.TimeField(verbose_name='hora fin')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Cliente')),
            ],
        ),
    ]
