# Generated by Django 2.1 on 2018-09-18 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSignatureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Turno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_incorporacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 15, 50, 16, 372989, tzinfo=utc), verbose_name='fecha de incorporación'),
        ),
    ]
