# Generated by Django 2.1 on 2018-09-18 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0002_auto_20180918_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('fecha', models.DateField(verbose_name='fecha del turno')),
                ('hora_inicio', models.TimeField(verbose_name='hora inicio')),
                ('duracion', models.IntegerField(verbose_name='duración')),
                ('hora_fin', models.TimeField(verbose_name='hora fin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_incorporacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 16, 2, 0, 752798, tzinfo=utc), verbose_name='fecha de incorporación'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='fecha del turno'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Cliente'),
        ),
    ]
