# Generated by Django 2.1 on 2018-09-18 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0008_auto_20180918_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha del turno')),
                ('hora_inicio', models.TimeField(verbose_name='hora inicio')),
                ('duracion', models.IntegerField(verbose_name='duración')),
                ('hora_fin', models.TimeField(verbose_name='hora fin')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_incorporacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 16, 12, 46, 309129, tzinfo=utc), verbose_name='fecha de incorporación'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Cliente'),
        ),
    ]
