# Generated by Django 2.1 on 2018-09-18 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0011_auto_20180918_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_incorporacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de incorporación'),
        ),
        migrations.AddField(
            model_name='casa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Cliente'),
        ),
    ]
