# Generated by Django 2.1 on 2018-09-18 22:25

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0013_auto_20180918_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
                ('fecha', models.DateField(verbose_name='fecha del turno')),
                ('duracion', models.IntegerField(verbose_name='duración')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='casa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='signature_date',
        ),
        migrations.AddField(
            model_name='prueba',
            name='prueba',
            field=jsignature.fields.JSignatureField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
