# Generated by Django 2.1 on 2018-09-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0014_auto_20180918_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
