# Generated by Django 2.1 on 2018-09-18 22:29

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0015_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba', jsignature.fields.JSignatureField()),
            ],
        ),
    ]
