# Generated by Django 2.1 on 2018-09-18 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0016_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
