# Generated by Django 2.1 on 2018-09-18 22:33

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0017_delete_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JSignatureModel',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='signature_date',
        ),
        migrations.AddField(
            model_name='sesion',
            name='firma',
            field=jsignature.fields.JSignatureField(default=''),
            preserve_default=False,
        ),
    ]
