# Generated by Django 2.1 on 2018-09-18 22:41

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0018_auto_20180918_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='firma',
            field=jsignature.fields.JSignatureField(blank=True, null=True),
        ),
    ]
