# Generated by Django 2.1 on 2018-09-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0019_auto_20180918_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre_y_apellido',
            field=models.CharField(max_length=75),
        ),
    ]
