# Generated by Django 2.1 on 2018-09-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0020_auto_20180918_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='lock_sig',
            field=models.BooleanField(default=False, verbose_name='Bloquear firma'),
            preserve_default=False,
        ),
    ]
