# Generated by Django 2.1 on 2018-09-21 22:13

from django.db import migrations, models
import django.db.models.deletion
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0021_sesion_lock_sig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', jsignature.fields.JSignatureField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='lock_sig',
        ),
        migrations.AddField(
            model_name='firma',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Sesion'),
        ),
    ]
