# Generated by Django 2.1 on 2018-09-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0022_auto_20180921_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='duracion',
            field=models.CharField(default=5, max_length=3, verbose_name='Duración'),
        ),
    ]
