# Generated by Django 2.1 on 2018-10-11 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0027_sesion_pagada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_sesiones', models.IntegerField(choices=[(1, '1 sesión'), (2, '2 sesiones'), (4, '4 sesiones'), (10, '10 sesiones')], verbose_name='Cantidad de sesiones')),
                ('tipo', models.IntegerField(choices=[(5, 'Suave'), (10, 'Fuerte')], verbose_name='Tipo')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
        migrations.AddField(
            model_name='sesion',
            name='actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sesión pack'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_incorporacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de incorporación'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='duracion',
            field=models.IntegerField(choices=[(5, '5 minutos'), (10, '10 minutos')], verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de la sesión'),
        ),
        migrations.AddField(
            model_name='pack',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabina.Cliente'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabina.Pack'),
        ),
    ]
