# Generated by Django 2.1 on 2018-10-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0028_auto_20181011_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabina.Responsable'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabina.Responsable'),
        ),
    ]
