# Generated by Django 2.1 on 2019-02-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0033_auto_20181029_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='proxima',
            field=models.IntegerField(default=1, verbose_name='Próxima sesión disponible'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabina.Cliente'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabina.Cliente'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabina.Pack'),
        ),
    ]
