# Generated by Django 2.1 on 2019-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabina', '0034_auto_20190214_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='proxima',
            field=models.PositiveIntegerField(default=1, verbose_name='Próxima sesión disponible'),
        ),
    ]
